### ISSUE TITLE
sharedmem.empty_like not running as parallel?

### ISSUE THREAD

**Issue by am-thyst** [rainwoodman/sharedmem#13]
I'm trying to run a code that performs a function for every point in this 4-dimensional array. It's very intensive, so will naturally take a long time to run. I tried using `mp.Array` and `mp.Manager`, which ran as parallel but didn't give me the expected result. So, I decided to try this `sharedmem.empty_like`:

```python

def func(abc, array):
  for j in range(int(abc)-1, int(abc)):
    for k in range(0, 241):
      for l in range(0, 480):
        temp_profile = np.array(sfc_t[j,k,l]) * units.kelvin
        pressure_profile = np.array((sfc_p[j,k,l], 950, 900, 850, 750, 700, 650, 600)) * units.hPa
        dewpoint_profile = np.array(sfc_dp[j,k,l]) * units.kelvin
        parcel_p = parcel_profile(pressure_profile, temp_profile, dewpoint_profile)
        parcel_p = parcel_p / units.kelvin
        parcel_p = np.array([sfc_t[j,k,l], parcel_p[0], parcel_p[1],
        parcel_p[2], parcel_p[3], parcel_p[4], parcel_p[5], parcel_p[6], parcel_p[7]])
        array[j, k, l, :] = parcel_p

if __name__ == '__main__':
    the_range = int(datetime_range)
    arra = np.zeros((int(datetime_range), 241, 480, 9))
    arrb = sharedmem.empty_like(arra)
    p = Process(target = func, args=(the_range, arrb))
    p.start()
    p.join()
```

And it seems to be running on only one core. Am I using the `sharedmem.empty_like` wrong for this example?

**Comment by rainwoodman** [comment]
If you only start a single process then you do only get one process.

empty_like only guarantees write access on the memory is reasonably defined from all forked processes. 

For your work-flow, I think you may want to use the map-reduce pattern via MapReduce -- like this:

https://github.com/rainwoodman/sharedmem/blob/master/sharedmem/sharedmem.py#L101

**Comment by am-thyst** [comment]
@rainwoodman thank you, I'll give it a try and come back if I have any problems!
